### PR TITLE
Add support for sqlalchemy 2

### PR DESCRIPTION
**Pull request by filias**
This PR adds support for sqlalchemy 2.

I followed the [docs](https://docs.sqlalchemy.org/en/14/changelog/migration_20.html) for migrating to version 2:

First I made my local environment ready by being able to run the tests (I used only [sqlite](https://hub.docker.com/r/keinos/sqlite3)). 
  - For that I had to upgrade `poetry` (I also tried to make a PR for that but it always failed in ci and I couldn't figure out the reason yet...). I also had to change the syntax of the `toml` file for github dependencies and bump the python version to >=3.7.

Then I turned on [RemovedIn20Warnings](https://docs.sqlalchemy.org/en/14/changelog/migration_20.html#migration-to-2-0-step-two-turn-on-removedin20warnings) and fixed those warnings (here is a list):
   - MovedIn20Warning: The ``declarative_base()`` function is now available as sqlalchemy.orm.declarative_base(). (deprecated since: 1.4) (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
  - RemovedIn20Warning: The legacy calling style of select() is deprecated and will be removed in SQLAlchemy 2.0.  Please use the new calling style described at select(). (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
  - RemovedIn20Warning: This Session located a target engine via bound metadata; as this functionality will be removed in SQLAlchemy 2.0, an Engine object should be passed to the Session() constructor directly. (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
  - RemovedIn20Warning: The Query.from_self() method is considered legacy as of the 1.x series of SQLAlchemy and will be removed in 2.0. The new approach is to use the orm.aliased() construct in conjunction with a subquery.  See the section "Selecting from the query itself as a subquery" in the 2.0 migration notes for an example. (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)

I added `future=True` to engine and sessionmaker. This was only in tests.

Finally I upgraded to sqlachemy 2.

@djrobstep I think I need your help here. I don't seem to be able to upgrade poetry. I tried also in a separate [PR](#76) but did not manage. The output of `poetry install` does not show me any errors but the step fails in ci. Locally I have everything working fine 🤔 I did try a lot of ideas but nothing helped me understand why install fails. Can you help me? I think it would be great if `sqlakeyset` support sqlalchemy 2.0 :) Thanks!

Update 1: I suspect an out of memory error in circleci 🤔 
Update 2: the problem was https://github.com/python-poetry/poetry/issues/7184 and was solved by passing --no-ansi to the poetry install command.

Note: we might need to change the tests if we want to support sqlalchemy < 1.4

### CODE REVIEW

**Comment by acarapetis** [comment]
Thanks for your effort!
We need to consider the best way forward regarding sqlalchemy-1 compatibility: I thought we'd need to bump our major version and drop support entirely, but from a quick look at your changes it seems we can pretty easily keep the same `select_page` API with backwards compatibility. I'll have a go at updating the tests to work with both versions (and perhaps add some new SQLAlchemy2-style ORM tests using `select_page`).

**Comment by acarapetis** [comment]
I've merged #78 to master, rebased this branch on master and squashed a bunch of commits.
There is much less change than I was expecting to be necessary. Having trouble getting tests to run, but looks like it might be an issue with sqlbag and sqlalchemy2, working on it.
To be sure I understand, is the only reason for the `sqla14`/`sqla20` split the fact that `sqlalchemy.engine.row.LegacyRow` no longer exists in `sqlalchemy==2`? If so, we can simplify this quite a bit.

**Comment by filias** [comment]
> I've merged #78 to master, rebased this branch on master and squashed a bunch of commits. There is much less change than I was expecting to be necessary. Having trouble getting tests to run, but looks like it might be an issue with sqlbag and sqlalchemy2, working on it.

That's really great :) Thank you for following up on this :)

> To be sure I understand, is the only reason for the `sqla14`/`sqla20` split the fact that `sqlalchemy.engine.row.LegacyRow` no longer exists in `sqlalchemy==2`? If so, we can simplify this quite a bit.

Yes, that was the reason. Great that it can be simplified 👍

**Comment by acarapetis** [comment]
As you can see I left the sqla14/sqla20 split more or less as you had it, just reorganized the files a little and made all imports explicit. Tests are passing with all sqlalchemy versions so I think we're good to go. I'm working on some additional stuff (type hints, asyncio support) on another branch but I'm going to go ahead and release this chunk now. Thanks again for your contribution!

**Review by acarapetis — APPROVED** [review]

**Comment by filias** [comment]
> As you can see I left the sqla14/sqla20 split more or less as you had it, just reorganized the files a little and made all imports explicit. Tests are passing with all sqlalchemy versions so I think we're good to go. I'm working on some additional stuff (type hints, asyncio support) on another branch but I'm going to go ahead and release this chunk now. Thanks again for your contribution!

Awesome 🎉  
Thank you so much for following up on this 👏 🚀

**Comment by jokull** [comment]
Wow - amazing effort!

**Pull request merged**
